FROM ubuntu:22.04

RUN apt-get update -y && apt-get install -y \
    git \
    ruby-full \
    libffi-dev \
    libssl-dev \
    libreadline-dev \
    zlib1g-dev \
    curl \
    shunit2 \
    jq \
    && rm -rf /var/lib/apt/lists/*

RUN gem install bashcov simplecov simplecov-cobertura

WORKDIR /conjur-circleci-orb

COPY . .

ENV COVERAGE=true

RUN chmod +x test/retrieve_secret_unit_test.sh
