services:
  openssl:
    image: cyberark/conjur
    container_name: openssl
    entrypoint:
     - openssl
     - req
     - -newkey
     - rsa:2048
     - -days
     - "365"
     - -nodes
     - -x509
     - -config
     - /tmp/conf/tls.conf
     - -extensions
     - v3_ca
     - -keyout
     - /tmp/conf/nginx.key
     - -out
     - /tmp/conf/nginx.crt
    volumes:
     - ../test/https_config/tls/:/tmp/conf:z

  database:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_HOST_AUTH_METHOD: password
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8432:5432"
    networks:
      - conjur

  conjur-leader:
    image: cyberark/conjur
    container_name: conjur-leader-1.mycompany.local
    command: server
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@database/postgres
      CONJUR_DATA_KEY: ${CONJUR_DATA_KEY}
      CONJUR_AUTHENTICATORS: authn-jwt/circleci
      CONJUR_TELEMETRY_ENABLED: 'false'
      CONJUR_API_RESOURCE_LIST_LIMIT_MAX: 5000
    depends_on:
    - database
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - ../test/integration/scripts/configure-conjur.sh:/scripts/configure-conjur.sh:ro
      - ../test/integration/data:/data
    networks:
      conjur:
        aliases:
          - conjur-leader-1.mycompany.local

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "8443:443"
    volumes:
       - ../test/https_config/default.conf:/etc/nginx/conf.d/default.conf:ro
       - ../test/https_config/tls:/etc/nginx/tls/:ro
    depends_on:
    - conjur-leader
    - openssl
    restart: on-failure
    networks:
      - conjur

  conjur-cli:
    extends:
      file: common-services.yml
      service: conjur-cli

  circleci-runner:
    extends:
      file: common-services.yml
      service: circleci-runner

networks:
  conjur:
    driver: bridge